apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: springboot-ingress
  namespace: onestop
spec:
  ingressClassName: nginx
  rules:
    - host: service.onestop.host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot
                port:
                  number: 51300
