apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: 0075841/onestop-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/onestopDB"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "0000"
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/ecommerce"
            - name: SPRING_DATASOURCE_PROFILE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: LoadBalancer  # Specify the service type (ClusterIP is default)
  ports:
    - port: 51300
      targetPort: 8080  # Map the service port to the container port
  selector:
    app: springboot
